version: '3.3'

services:
  app:
    build: .
    ports:
      - '80:80'
    links:
      - database
    volumes:
      - .:/app
    command: >
      bash -c "python ./manage.py makemigrations
      && python ./manage.py migrate
      && python ./manage.py runserver 0.0.0.0:80"
    depends_on:
      - "database"

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
