version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    links:
      - database
    volumes:
      - .:/app
    depends_on:
      - "database"

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
