# Generated by Django 3.0.8 on 2020-07-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200712_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='transition',
            new_name='transcription',
        ),
    ]
