# Generated by Django 3.0.8 on 2020-07-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200712_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='polls.Theme'),
        ),
    ]
